import { v4 as uuidv4 } from "uuid";

export const recomendedProduct = [
  {
    id: uuidv4(),
    name: "Lemon curd tart with blackberry cream",
    fullName: "Lemon curd tart with blackberry cream",
    imgProd: require("./imgs/product/cakes/blackberryfeature1_zps6d5c6b22.jpg"),
    price: "6$",
    typeProd: "cakes",
    data: "Blackberry cake is a fluffy dough with a juicy blackberry filling, topped with a light cream and fresh berries, which mixes sweet and sour flavors.",
  },
  {
    id: uuidv4(),
    name: "Choco cupcakes with pistachio cream and raspberry filling",
    fullName: "Chocolate cupcakes with pistachio cream and raspberry filling",
    imgProd: require("./imgs/product/cakes/chocoCupcakes.jpg"),
    price: "7$",
    typeProd: "Chocolate",
    data: "Chocolate cupcake with pistachio cream and raspberry filling: a rich, velvety treat, blending chocolate, fragrant pistachio, and fresh raspberry in perfect harmony.",
  },
  {
    id: uuidv4(),
    name: "'Choco cherry tenderness' with cocoa cake layers 500g",
    fullName: "Cakes 'Choco cherry tenderness' with cocoa cake layers 500g",
    imgProd: require("./imgs/product/cake/ChocoCherryTender.jpg"),
    price: "8.50$",
    typeProd: "cakes",
    data: '"Choco cherry tenderness" combines soft chocolate cakes with cherry jam, airy curd cream, juicy cherries, and chocolate chips for a rich, balanced taste.',
  },
  {
    id: uuidv4(),
    name: "Set Craft Candy 'Sweet Memories'",
    fullName: "Set Craft Candy 'Sweet Memories' 12 pieces",
    imgProd: require("./imgs/product/candies/candyBuffet.webp"),
    price: "10.20$",
    typeProd: "Candies",
    data: "CandyBuffet is a Ukrainian manufacturer of chocolates with unique fillings for connoisseurs of taste. The set includes: Baileys-coffee-cardamom, passion fruit, etc.",
  },
  {
    id: uuidv4(),
    name: "Craft Candies 'Love Letters' with white chocolate",
    fullName: "Craft Candies 'Love Letters' with white chocolate 200g",
    imgProd: require("./imgs/product/candies/lvovCandy.webp"),
    price: "11$",
    typeProd: "Candies",
    data: "These milk chocolate candies feature a delicate texture and melt-in-your-mouth goodness, perfect for treating yourself or your loved ones.",
  },
  {
    id: uuidv4(),
    name: "Tartlets with milk-top cream and fresh berries",
    fullName: "Tartlets with milk-top cream and fresh berries",
    imgProd: require("./imgs/product/cakes/tartiliaWithBerry.jpg"),
    price: "5$",
    quantity: "6",
    typeProd: "Cakes",
    data: "Delicate berry tartlets made with low-fat cottage cheese cream, featuring natural sweetness and no artificial additives—perfect for everyone.",
  },
];

export const popularProd = [
  {
    id: uuidv4(),
    name: "Cakes 'Choco cherry tenderness' with cocoa cake layers 500g",
    imgProd: require("./imgs/product/cake/ChocoCherryTender.jpg"),
    price: "8.5$",
    typeProd: "Cakes",
    data: '"Choco cherry tenderness" is an exquisite combination of delicate chocolate cakes soaked in cherry jam and airy curd cream. Juicy cherries add a slight sourness, and chocolate chips on top complete the flavor, making each bite truly luxurious and harmonious.',
  },
  {
    id: uuidv4(),
    name: "Varietal chocolate with different flavors 100 g packaging",
    imgProd: require("./imgs/product/choco/sortChoco.jpg"),
    price: "3.11$",
    typeProd: "Chocolate",
    data: "If you want to eat a few chocolates, we can offer you a set of varietal chocolate. There is white, milk, and dark chocolate with different fillings: nuts, dried fruits, berries and much more",
  },
  {
    id: uuidv4(),
    name: "Tartlets with milk-top cream and fresh berries",
    imgProd: require("./imgs/product/cakes/tartiliaWithBerry.jpg"),
    price: "5$",
    typeProd: "Cakes",
    data: "These delicate tartlets with berries are sure to appeal to everyone. They are moderately sweet, there are no unnecessary dyes or chemical additives. Only low-fat cottage cheese cream and delicious berries.",
  },
  {
    id: uuidv4(),
    name: "Craft Candies 'Almond-apple harmony' 220g",
    imgProd: require("./imgs/product/candies/appleAlmondCandies.jpg"),
    price: "4.83$",
    typeProd: "Candies",
    data: "If you want to please your loved one, or you just want to please yourself, then these milk chocolate candies are definitely right for you! Delicate texture, melt-in-your-mouth chocolate with a variety of additives to suit your taste",
  },
];

export const cakes = [
  {
    id: uuidv4(),
    name: "Lemon curd tart with blackberry cream",
    imgProd: require("./imgs/product/cakes/blackberryfeature1_zps6d5c6b22.jpg"),
    price: 6,
    defprice: 6,
    quantity: 1,
    typeProd: "cakes",
    data: "Blackberry cake is a delicate delicacy with fluffy dough and juicy blackberry filling, decorated with light cream and fresh berries, which combines sweetness and sourness in every bite. The dough itself uses lemon and orange zest, which adds not only a pleasant aroma, but also a fresh taste",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Chocolate cupcakes with pistachio cream and raspberry filling",
    imgProd: require("./imgs/product/cakes/chocoCupcakes.jpg"),
    price: 7,
    defprice: 7,
    quantity: 1,
    typeProd: "cakes",
    data: "Chocolate cupcakes with pistachio cream and raspberry filling are a delicate combination of velvety chocolate, fragrant pistachio cream and fresh raspberry filling, embodying sweet perfection in every bite",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Red Velvet",
    imgProd: require("./imgs/product/cakes/redVelvet.jpg"),
    price: 5.8,
    defprice: 5.8,
    quantity: 1,
    typeProd: "cakes",
    data: 'Delicate cakes "Red Velvet" with a velvety texture and rich cocoa flavor, decorated with an airy cheese glaze, create the perfect combination of sweetness and creamy tenderness',
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Cakes with raspberry mousse",
    imgProd: require("./imgs/product/cakes/cakesRaspberryMousse.jpg"),
    price: 6.51,
    defprice: 6.51,
    quantity: 1,
    typeProd: "cakes",
    data: "Delicious and delicate cakes with raspberry mousse and pieces of berries in dough will delight you even on the most difficult day. They have the perfect balance between sweetness and sourness. Each cake is decorated with raspberries on top",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Blueberry cake with cheese cream",
    imgProd: require("./imgs/product/cakes/blueberryCake.jpg"),
    price: 7,
    defprice: 7,
    quantity: 1,
    typeProd: "cakes",
    data: "Sweet and fragrant cakes with blueberries and delicate cheese cream are sure to surprise you. We added cocoa to the dough for an exquisite taste and aroma, and inside the cake itself there is fresh blueberry jam, which will give a slight sourness",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Tartlets with milk-top cream and fresh berries",
    imgProd: require("./imgs/product/cakes/tartiliaWithBerry.jpg"),
    price: 7,
    defprice: 7,
    quantity: 1,
    typeProd: "cakes",
    data: "These delicate tartlets with berries are sure to appeal to everyone. They are moderately sweet, there are no unnecessary dyes or chemical additives. Only low-fat cottage cheese cream and delicious berries.",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Mint cream cakes garnished with berries 12 piece",
    imgProd: require("./imgs/product/cakes/41dbd002cffa4386397337ccf8e324f8.jpg"),
    price: 7.64,
    defprice: 7.64,
    quantity: "1",
    typeProd: "cakes",
    data: "Delicate cakes with a slight sour taste thanks to mint cream with the addition of lime juice. They are topped with juicy blueberries and blackberries that add freshness to the flavor. The décor is completed by a fresh blackberry leaf, which gives the cakes an exquisite look.",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Sponge cakes with raspberry mousse",
    imgProd: require("./imgs/product/cakes/bescvit-cakes.jpg"),
    price: 6.67,
    defprice: 6.67,
    quantity: 1,
    typeProd: "cakes",
    data: "Sponge cake with freshly ground raspberries and raspberry-cottage cheese mousse. The filling itself (raspberries and mousse) with the addition of jelly or agar agar to create a round shape. This dessert is moderately sweet, but very delicate and tasty. It is decorated with raspberries and a little cottage cheese cream on top",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "'Cherry Tenderness' is a diet cake without sugar",
    imgProd: require("./imgs/product/cakes/cakesWithCherry.webp"),
    price: 4.85,
    defprice: 4.85,
    quantity: 1,
    typeProd: "cakes",
    data: "Cherry Tenderness - is a light and airy cake created especially for people who care about their blood sugar levels. The combination of tender dough and bright, juicy cherries makes this dessert not only delicious, but also safe for those who follow a diet with a low glycemic index. Fresh cherries give the cake a special freshness, and a slight sweetness is achieved due to natural sweeteners.",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Pistachio éclair 3p",
    imgProd: require("./imgs/product/cakes/pistachioEcler.jpg"),
    price: 4.26,
    defprice: 4.26,
    quantity: 1,
    typeProd: "cakes",
    data: "Pistachio eclairs are an exquisite confectionery that combines lightness and tenderness. They have a crispy, golden crust made with classic custard dough and are filled with a fluffy pistachio cream that has a rich nutty flavor and a slight sweetness.",
    ingredients: [
      "Flour",
      "Milk",
      "Butter",
      "Eggs",
      "Sugar ",
      "Pinch of salt",
      "Starch (corn or potato)",
      "Chocolate",
      "Pistachios",
      "Cream",
    ],
    supplements: [
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Raspberry éclair 3p",
    imgProd: require("./imgs/product/cakes/raspberryEcler.webp"),
    price: 4,
    defprice: 4,
    quantity: 1,
    typeProd: "cakes",
    data: "Raspberry éclair is an exquisite dessert made of puff pastry filled with cottage cheese and raspberry jam. It is covered with milk chocolate and decorated with pieces of frozen raspberries. This sweet delicacy perfectly combines a delicate taste and bright raspberry sourness",
    ingredients: [
      "Flour",
      "Milk",
      "Butter",
      "Eggs",
      "Sugar ",
      "Pinch of salt",
      "Starch (corn or potato)",
      "Chocolate",
      "Vanilla extract",
      "Cream",
      "Frozen raspberries",
      "Cottage cheese for cream",
    ],
    supplements: [
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
      {
        id: uuidv4(),
        nameProd: "fresh raspberries for garnish",
        price: 5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Chocolate éclair 3p",
    imgProd: require("./imgs/product/cakes/classicEcler.jpg"),
    price: 3.56,
    defprice: 3.56,
    quantity: 1,
    typeProd: "cakes",
    data: "Eclairs are custard pastries made of flour, water, butter and eggs. They are usually filled with custard, which is made with milk, eggs, sugar and starch. Chocolate or sugar glaze is used to decorate eclairs. Delicate and delicious cakes will help you get a taste of French culture",
    ingredients: [
      "Flour",
      "Milk",
      "Butter",
      "Eggs",
      "Sugar ",
      "Pinch of salt",
      "Starch (corn or potato)",
      "Chocolate",
      "Vanilla extract",
      "Cream",
    ],
    supplements: [
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
];

export const cake = [
  {
    id: uuidv4(),
    name: "Cakes 'Choco cherry tenderness' with cocoa cake layers 500g",
    imgProd: require("./imgs/product/cake/ChocoCherryTender.jpg"),
    price: 8.5,
    defprice: 8.5,
    quantity: 1,
    typeProd: "cake",
    data: '"Chocolate cherry tenderness" is an exquisite combination of delicate chocolate cakes soaked in cherry jam and airy curd cream. Juicy cherries add a slight sourness, and chocolate chips on top complete the flavor, making each bite truly luxurious and harmonious.',
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Classical Napoleon",
    imgProd: require("./imgs/product/cake/napoleon.webp"),
    price: 7.89,
    defprice: 7.89,
    quantity: 1,
    typeProd: "cake",
    data: "Napoleon cake is a delicate and crispy dessert consisting of many thin layers of puff pastry layers. These cakes are soaked in airy custard, which gives them softness and rich taste.",
    ingredients: [
      "Butter",
      "Flour",
      "Milk",
      "Eggs",
      "Sugar",
      "Pinch of salt",
      "Cream",
      "Cottage cheese",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
      {
        id: uuidv4(),
        nameProd: "Berries for decoration",
        price: 5,
      },
      {
        id: uuidv4(),
        nameProd: "Chocolate chips",
        price: 2.3,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Cake Red velvet",
    imgProd: require("./imgs/product/cake/redValvetCake.jpg"),
    price: 8.2,
    defprice: 8.2,
    quantity: 1,
    typeProd: "cake",
    data: "Red Velvet Cake is an exquisite dessert delicacy that attracts attention with its bright, rich red color and delicate texture. This cake is a combination of an airy chocolate crust with a light creamy ricotta cheese or cream cheese base.",
    ingredients: [
      "Flour",
      "Sugar",
      "Buttermilk",
      "Red food coloring",
      "Cocoa powder",
      "Eggs",
      "Butter",
      "Cream cheese",
      "Powdered sugar",
    ],
    supplements: [
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
      {
        id: uuidv4(),
        nameProd: "Fresh berries",
        price: 5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: 'Strawberry cheesecake "Sweet Love"',
    imgProd: require("./imgs/product/cake/hurtCakes.jpg"),
    price: 9,
    defprice: 9,
    quantity: 1,
    typeProd: "cake",
    data: "Cheesecake with strawberry filling and heart jelly is the perfect choice for a special gift for a loved one. The delicate texture of cream cheese combined with a thin, slightly crispy cake creates a harmony of flavors, and the sweet and fragrant strawberry filling adds freshness and slight acidity. The top layer is decorated with a transparent heart-shaped jelly, inside which whole fresh strawberries are hidden. This cake not only pleases with its exquisite taste, but also looks spectacular, bringing special warmth and care to every bite.",
    ingredients: [
      "Sugar Cookies",
      "Butter",
      "cream cheese",
      "cream",
      "Eggs",
      "Sugar",
      "Fresh strawberries",
      "Gelatine",
    ],
    supplements: [
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Mousse cake 'Blueberry cloud'",
    imgProd: require("./imgs/product/cake/BlueberryMouseCake.jpg"),
    price: 8.5,
    defprice: 8.5,
    quantity: 1,
    typeProd: "cake",
    data: "Blueberry Cloud Cake is a dessert with a base of crushed cocoa cake, a delicate curd and cheese layer and a light blueberry mousse. A perfect combination of chocolate bitterness, creamy tenderness and berry freshness.",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Whole Wheat flour", price: 3 },
      { id: uuidv4(), nameProd: "Coconut flour", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Carrot Cake with Nuts and Coconut Cream (Vegan)",
    imgProd: require("./imgs/product/cake/carrotCake.jpg"),
    price: 8.2,
    defprice: 8.2,
    quantity: 1,
    typeProd: "cake",
    data: "Carrot cake with nuts and coconut cream is a delicate, moist and flavorful dessert that is perfect for any occasion. Sweet grated carrots add natural sweetness and bright color to the cake, while nuts add a crunchy texture. Coconut cream serves as a wonderful light cream that goes well with the spicy taste of carrots. This cake can be served for the holidays as well as for a regular day, enjoying every bite.",
    ingredients: [
      "Flour",
      "Carrot",
      "Nuts (walnuts or pecans)",
      "Baking powder",
      "Ground cinnamon ",
      "Sugar",
      "Plant-based milk",
      "Coconut cream",
      "Coconut flakes",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Almond flour", price: 3 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Apple cake for vegans with cocoa",
    imgProd: require("./imgs/product/cake/chocoBananCake.jpg"),
    price: 8,
    defprice: 8,
    quantity: 1,
    typeProd: "cake",
    data: "Perfect for vegans, this delicate apple cake combines the rich chocolate flavor with the freshness of apples. The basis for the dough is flour, which, in tandem with applesauce, adds moisture and a light fruity note. Plant-based milk and vegetable oil provide softness and airiness, while cocoa powder adds a deep chocolate hue.",
    ingredients: [
      "Flour",
      "Applesauce",
      "Plant-based milk",
      "Vegetable oil",
      "Cocoa powder",
      "Sugar",
      "bitter or dark chocolate",
      "coconut cream",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Almond flour", price: 3 },
      { id: uuidv4(), nameProd: "Oat flour", price: 3 },
      { id: uuidv4(), nameProd: "Fresh berries", price: 5 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Cake Esterházy",
    imgProd: require("./imgs/product/cake/esterxazi.jpg"),
    price: 9.2,
    defprice: 9.2,
    quantity: 1,
    typeProd: "cake",
    data: "Esterházy cake is a classic Hungarian dessert that stands out for its elegant look and exquisite taste. Traditionally, it consists of several thin layers based on nutty meringue, usually almonds or hazelnuts, which alternate with a custard-based buttercream with the addition of cognac or rum, which gives the dessert a rich flavor. The cakes have a light crispy texture, which, in combination with a delicate, slightly sweet cream, creates a harmony of flavors",
    ingredients: [
      "Flour",
      "Ground almonds",
      "Milk",
      "Butter",
      "Eggs",
      "Sugar",
      "Cognac or rum",
      "White Chocolate",
      "Dark chocolate – 50 g (for drawing)",
      "Almond petals",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Almond flour", price: 3 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      { id: uuidv4(), nameProd: "Chopped nuts", price: 5.3 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
  {
    id: uuidv4(),
    name: "Cake Gâteau Caramel",
    imgProd: require("./imgs/product/cake/GâteauCaramel.jpg"),
    price: 8.59,
    defprice: 8.59,
    quantity: 1,
    typeProd: "cake",
    data: "The Gâteau Caramel cake consists of several layers, each of which is soaked in a rich caramel flavor. It usually consists of soft sponge cakes soaked in caramel syrup and cream made on the basis of cream and caramel. The cake is often topped with caramel frosting, whipped cream, or chunks of caramel. The sweet and slightly salty caramel flavor is perfectly balanced with the delicate texture of the cream, which makes it incredibly delicious.",
    ingredients: [
      "Flour",
      "Cream",
      "Chocolate chips",
      "Butter",
      "Eggs",
      "Sugar",
      "Baking powder",
      "Liquid caramel",
      "Cottage cheese",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "Almond flour", price: 3 },
      { id: uuidv4(), nameProd: "Vanilla extract", price: 2 },
      { id: uuidv4(), nameProd: "Gluten-free flour", price: 5.3 },
      {
        id: uuidv4(),
        nameProd: "Natural sweetener (erythritol or stevia)",
        price: 3.5,
      },
    ],
  },
];

export const chocolate = [
  {
    id: uuidv4(),
    name: 'Chocolate "Deep Galaxy"',
    imgProd: require("./imgs/product/choco/greatChoco.jpg"),
    price: 4.12,
    defprice: 4.12,
    quantity: 1,
    typeProd: "chocolate",
    data: "Chocolate Deep Galaxy is a magical white chocolate that transports you to the vast expanse of the galaxy. Delicate chocolate, colored in deep blue and light blue shades, reminds of the starry sky and mysterious space. Inside each piece is a sweet blueberry filling, which gives a rich taste and a memorable aroma. On top, the chocolate is decorated with delicate splashes of white chocolate that create the effect of star rain, and coconut balls",
    ingredients: [
      "White chocolate",
      "Blue food coloring",
      "Fresh blueberries",
      "Coconut flakes",
    ],
  },
  {
    id: uuidv4(),
    name: "White chocolate with assorted nuts 100g",
    imgProd: require("./imgs/product/choco/whitiChoco.jpg"),
    price: 3.3,
    defprice: 3.3,
    quantity: 1,
    typeProd: "chocolate",
    data: "White chocolate with assorted nuts is an exquisite dessert that combines the delicate taste of white chocolate and the crunchy textures of a variety of nuts. Each piece of this chocolate will give you a real symphony of flavors and textures. The sweetness of white chocolate is in perfect harmony with nuts - almonds, hazelnuts, walnuts and cashews, creating a unique combination that will delight true connoisseurs of sweets.",
    ingredients: [
      "White chocolate",
      "Almonds",
      "Hazelnuts",
      "Walnuts",
      "Cashews",
    ],
  },
  {
    id: uuidv4(),
    name: "Varietal chocolate with different flavors 100 g packaging",
    imgProd: require("./imgs/product/choco/sortChoco.jpg"),
    price: 3.11,
    defprice: 3.11,
    quantity: 1,
    typeProd: "chocolate",
    data: "If you want to eat a few chocolates, we can offer you a set of varietal chocolate. There is white, milk, and dark chocolate with different fillings: nuts, dried fruits, berries and much more",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
  },
  {
    id: uuidv4(),
    name: 'Milk Chocolate "Citrus Harmony"',
    imgProd: require("./imgs/product/choco/orangeChocolate.jpg"),
    price: 5.3,
    defprice: 5.3,
    quantity: 1,
    typeProd: "chocolate",
    data: "Citrus Harmony - is a delicate milk chocolate with bright pieces of dried orange and crunchy nuts. It is a harmonious combination of sweetness and citrus freshness that will give you joy in every bite",
    ingredients: [
      "Milk chocolate (Cocoa butter, Cocoa beans)",
      "Dried Orange",
      "Nuts (almonds, walnuts)",
    ],
  },
  {
    id: uuidv4(),
    name: "Dubai Chocolate 100g",
    imgProd: require("./imgs/product/choco/dybaiChoco.jpg"),
    price: 7.1,
    defprice: 7.1,
    quantity: 1,
    typeProd: "chocolate",
    data: "Dubai chocolate is a gourmet treat that combines rich flavors with unique oriental flavors. It is made from quality cocoa beans and is supplemented with a variety of additives such as pistachios, dates, and spices, making it the perfect treat for sweet connoisseurs.",
    ingredients: [
      "Milk chocolate (Cocoa butter, Cocoa beans)",
      "Dates",
      "Pistachios, almonds",
      "Vanilla extract",
    ],
    supplements: [
      { id: uuidv4(), nameProd: "White chocolate decorations", price: 1.6 },
      { id: uuidv4(), nameProd: "Crushed nuts", price: 4 },
    ],
  },
  {
    id: uuidv4(),
    name: 'Milk chocolate "Raspberry Elegy"',
    imgProd: require("./imgs/product/choco/raspberryChocolate.jpg"),
    price: 5.1,
    defprice: 5.1,
    quantity: 1,
    typeProd: "chocolate",
    data: 'Immerse yourself in the world of delicate taste with "Raspberry Elegy" chocolate. This exquisite milk chocolate is enriched with the sweetness of juicy raspberries and the crunchy texture of crushed nuts. Each bite is a harmony of sweet and nutty, creating an unforgettable culinary experience that awakens the senses and pleases the soul.',
    ingredients: [
      "Milk chocolate (Cocoa butter, Cocoa beans)",
      "Dates",
      "Pistachios, almonds",
      "Vanilla extract",
    ],
  },
];

export const candies = [
  {
    id: uuidv4(),
    name: "Craft Candies 'Love Letters' with white chocolate 200g",
    imgProd: require("./imgs/product/candies/lvovCandy.webp"),
    price: 11,
    defprice: 11,
    typeProd: "candies",
    data: "If you want to please your loved one, or you just want to please yourself, then these milk chocolate candies are definitely right for you! Delicate texture, melt-in-your-mouth chocolate with a variety of additives to suit your taste",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
  },
  {
    id: uuidv4(),
    name: "Set Craft Candy 'Sweet Memories' 12 pieces",
    imgProd: require("./imgs/product/candies/candyBuffet.webp"),
    price: 10.2,
    defprice: 10.2,
    typeProd: "candies",
    data: "CandyBuffet is Ukrainian manufacturer of chocolates with unique author's fillings, created for those who appreciate taste and sophistication. This set will contain sweets with the following flavors: Baileys - coffee - cardamom; Passion fruit - freeze-dried corn; Ecuador - pink pepper; Marshmallow - lime; Linden - mint; Coconut - Matcha",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
  },
  {
    id: uuidv4(),
    name: "Set 'Sweet Memories Candy' 39 pieces",
    imgProd: require("./imgs/product/candies/candyBuffet2.webp"),
    price: 10.2,
    defprice: 10.2,
    typeProd: "candies",
    data: "CandyBuffet is Ukrainian manufacturer of chocolates with unique author's fillings, created for those who appreciate taste and sophistication. This set will contain sweets with the following flavors: Baileys - coffee - cardamom; Passion fruit - freeze-dried corn; Ecuador - pink pepper; Marshmallow - lime; Linden - mint; Coconut - Matcha",
    ingredients: [
      "Almond flour",
      "Coconut oil",
      "Fresh cherries",
      "Baking powder",
      "Eggs",
      "Sugar",
      "Yeast",
      "Pinch of salt",
    ],
  },
  {
    id: uuidv4(),
    name: '"Golden Moment" Candies  320g',
    imgProd: require("./imgs/product/candies/vintageCandi.jpg"),
    price: 8.3,
    defprice: 8.3,
    quantity: 1,
    typeProd: "candies",
    data: "Assorted candies are a real masterpiece of sweet art, which combines sophistication and sophistication. It consists of three types of chocolate: black, white and milk. Each candy is decorated with delicate gold patterns made in the Venetian style, which gives them a special charm and luxury. The chocolate assortment amazes with its variety of flavors and textures: from the rich bitterness of dark chocolate to the delicate sweetness of milk chocolate and the lightness of white.",
    ingredients: [
      "Dark chocolate",
      "Milk chocolate",
      "White Chocolate",
      "Cocoa butter",
      "Nut filling",
      "Berry puree",
      "Coffee cream",
    ],
  },
  {
    id: uuidv4(),
    name: "Craft Candies 'Almond-apple harmony' 220g",
    imgProd: require("./imgs/product/candies/appleAlmondCandies.jpg"),
    price: 6.24,
    defprice: 6.24,
    quantity: 1,
    typeProd: "candies",
    data: "If you want to please your loved one, or you just want to please yourself, then these milk chocolate candies are definitely right for you! Delicate texture, melt-in-your-mouth chocolate with a variety of additives to suit your taste",
    ingredients: ["Appple", "Almond", "Milk chocolate"],
  },
  {
    id: uuidv4(),
    name: "Scarlet Passion Candy",
    imgProd: require("./imgs/product/candies/hurtCandi.jpg"),
    price: 7.23,
    defprice: 7.23,
    quantity: 1,
    typeProd: "candies",
    data: "Each candy is made with love and care so that it retains a rich taste. Juicy cherries, blueberries and currants, harvested in the perfect combination, fill every heart. Cherries give sweetness with a slight sourness, blueberries add their delicate texture, and currants bring bright freshness and light astringency. All this is complemented by exotic rum, which gives the dessert a unique depth and character. The notes of rum are perfectly combined with the berry filling, creating an unforgettable taste.",
    ingredients: [
      "Dark chocolate",
      "Fresh cherries",
      "Fresh blueberries",
      "Fresh blackcurrants",
      "Rum",
    ],
  },
];

export const macaroon = [
  {
    id: uuidv4(),
    name: "Raspberry macaroons 6p",
    imgProd: require("./imgs/product/macaroon/raspberryMacaron.jpg"),
    price: 6.7,
    defprice: 6.7,
    typeProd: "macaroon",
    data: "Raspberry pasta is an exquisite confectionery with a delicate crispy crust and soft filling. These airy cakes are colored bright raspberries and filled with aromatic cream with a rich raspberry flavor that gives them a refreshing sourness.",
    ingredients: [
      "Almond flour",
      "Powdered sugar",
      "Glair",
      "Fresh or frozen raspberries",
      "Vanilla extract",
      "Sugar",
      "Butter",
      "Food coloring",
    ],
  },
  {
    id: uuidv4(),
    name: "Set Macaroon Symphony 9p",
    imgProd: require("./imgs/product/macaroon/asortiMacaroon.jpg"),
    price: 11.8,
    defprice: 11.8,
    typeProd: "macaroon",
    data: "Raspberry pasta is an exquisite confectionery with a delicate crispy crust and soft filling. These airy cakes are colored bright raspberries and filled with aromatic cream with a rich raspberry flavor that gives them a refreshing sourness.",
    ingredients: [
      "Almond flour",
      "Powdered sugar",
      "Glair",
      "Fresh or frozen raspberries",
      "Vanilla extract",
      "Sugar",
      "Butter",
      "Food coloring",
    ],
  },
  {
    id: uuidv4(),
    name: "Pistachio macaroons 6p",
    imgProd: require("./imgs/product/macaroon/PistachioMacaroon.jpg"),
    price: 7.2,
    defprice: 7.2,
    typeProd: "macaroon",
    data: "Pistachio macaroon is an exquisite confectionery that amazes with its delicate taste and bright color. With a smooth surface and a distinctive crispy crust, these small, round brownies have a thin and soft texture on the inside. The delicate pistachio flavor goes well with the sweet cream, which is often made with pistachio oil or paste.",
    ingredients: [
      "Almond flour",
      "Powdered sugar",
      "Glair",
      "Vanilla extract",
      "Sugar",
      "Butter",
      "Food coloring",
      "Pistachio paste",
      "50 grams of milk",
    ],
  },
  {
    id: uuidv4(),
    name: "Coffee Macaroons 6p",
    imgProd: require("./imgs/product/macaroon/coffeMararoon.webp"),
    price: 6.2,
    defprice: 6.2,
    typeProd: "macaroon",
    data: "Coffee macaroons are exquisite French sweets with a delicate crispy crust and a soft, melt-in-your-mouth filling. Their delicate, slightly nutty taste is perfectly emphasized by the aroma of freshly brewed coffee. These macaroons not only delight the eye with their bright palette, but also give incredible pleasure with every bite.",
    ingredients: [
      "Almond flour",
      "Powdered sugar",
      "Glair",
      "Vanilla extract",
      "Sugar",
      "Butter",
      "Cocoa Powder",
      "Coffee Extract",
      "Dark chocolate",
      "Cream",
      "Instant coffee",
    ],
  },
  {
    id: uuidv4(),
    name: "Macaroon hearts 6p",
    imgProd: require("./imgs/product/macaroon/BerryMacarons.jpg"),
    price: 8.2,
    defprice: 8.2,
    typeProd: "macaroon",
    data: "Heart-shaped berry macaroons are the perfect sweet treat for romantic moments! Delicate almond cakes, filled with light cottage cheese cream with a rich taste of raspberries and strawberries, will delight you with their bright color and refreshing taste. Not only do these macaroons taste delicious, but they're also a real addition to any table.",
    ingredients: [
      "Almond flour",
      "Powdered sugar",
      "Glair",
      "Vanilla extract",
      "Sugar",
      "Butter",
      "Food coloring",
      "Curd",
      "Berries (raspberries, strawberries)",
    ],
  },
  {
    id: uuidv4(),
    name: "Macarons with lemon and lime 6p",
    imgProd: require("./imgs/product/macaroon/limeMacaroon.jpg"),
    price: 7.7,
    defprice: 7.7,
    typeProd: "macaroon",
    data: "Lime macaroons are gourmet confections with a crispy crust and a tender, chewy texture. Bright green or yellow, they are filled with refreshing lime curd, which combines sweetness and a slight sourness.",
    ingredients: [
      "Almond flour",
      "Powdered sugar",
      "Glair",
      "Vanilla extract",
      "Sugar",
      "Butter",
      "Food coloring",
      "Freshly squeezed lemon juice",
      "Lime zest",
      "Cottage cheese cream",
    ],
  },
];
